# Generated by Django 4.1 on 2022-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_birth_date_remove_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
