# Generated by Django 4.1 on 2022-09-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_name_user_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('masculine', 'Masculino'), ('feminine', 'feminino'), ('other', 'outro')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
