# Generated by Django 4.1 on 2022-09-30 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 30, 20, 35, 21, 477354)),
        ),
    ]
