# Generated by Django 4.1 on 2022-11-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='campo_qualquer',
        ),
    ]
