# Generated by Django 4.1 on 2022-11-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Masculino', 'masculine'), ('Feminino', 'feminine'), ('Outro', 'other')], max_length=20, null=True),
        ),
    ]
