# Generated by Django 4.1 on 2022-11-22 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_image_url'),
        ('user', '0023_alter_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfProductsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('listOfProducts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.listofproducts')),
            ],
        ),
    ]
