# Generated by Django 4.1 on 2022-11-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_listofproductsproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListOfProductsProducts',
        ),
    ]
