# Generated by Django 4.1.1 on 2022-09-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.FloatField()),
                ('creation_date_price', models.DateTimeField(auto_now_add=True)),
                ('update_date_price', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='creation_date',
            new_name='creation_date_product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='update_date',
            new_name='update_date_product',
        ),
        migrations.CreateModel(
            name='HistoricPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_historic', models.FloatField()),
                ('creation_date_historic_price', models.DateTimeField(auto_now_add=True)),
                ('update_date_historic_price', models.DateTimeField(auto_now=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.price')),
                ('supermarket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.supermarket')),
            ],
        ),
    ]
