# Generated by Django 4.1.1 on 2022-09-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicprice',
            name='price',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
