# Generated by Django 4.1.1 on 2022-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_creation_date_historic_price_historicprice_alteration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name_city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name_product',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name_state',
            new_name='state_name',
        ),
        migrations.RenameField(
            model_name='supermarket',
            old_name='name_supermarket',
            new_name='supermarket_name',
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='complement',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
