# Generated by Django 4.1.1 on 2022-09-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_birth_date'),
        ('product', '0005_rename_name_category_category_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
