# Generated by Django 4.1.1 on 2022-09-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
