# Generated by Django 4.1.1 on 2022-09-24 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_historicprice_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
