# Generated by Django 4.1.1 on 2022-09-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
