# Generated by Django 4.1 on 2022-10-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_historicprice_supermarket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
    ]
