# Generated by Django 4.1 on 2022-11-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_historicprice_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.supermarket')),
            ],
        ),
    ]
