# Generated by Django 4.1 on 2022-11-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productsupermarket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSupermarket',
        ),
    ]
