# Generated by Django 4.1 on 2022-11-08 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_delete_productsupermarket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supermarket',
        ),
        migrations.AddField(
            model_name='product',
            name='supermarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.supermarket'),
        ),
    ]
