# Generated by Django 4.1 on 2022-11-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='fotos/default/índice.png', null=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
